# Test and build for deployment

name: BuildTestDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline:
    name: Install, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@master
      
      - name: install dependencies
        run: npm install

      - name: run unit test
        if: success()
        run: npm run test

      - name: run build 
        if: success()
        run: npm run build