name: BuildTestDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline:
    name: Install, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      
      - name: install dependencies
        run: ./bin/installDependencies.sh

      - name: run unit test
        if: success()
        run: ./bin/unitTestExtension.sh

      - name: run build 
        if: success()
        env:
            GIT_HUB_RUN_NUMBER: ${{ github.run_number }}
        run: ./bin/buildExtension.sh
        
      - name: Create Production Package
        uses: actions/upload-artifact@v2
        with:
          name: ChromeExtension.Production
          path: ./dist.production/
      
      - name: Create Development Package
        uses: actions/upload-artifact@v2
        with:
          name: ChromeExtension.Development
          path: ./dist.development/

      - name: Chrome Store listing artifact
        uses: actions/upload-artifact@v2
        with:
          name: StoreListing
          path: ./store_listing/
          
      - name: Code Coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: CodeCoverage
          path: ./coverage/

