name: BuildTestDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline:
    name: Install, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      
      - name: install dependencies
        working-directory: ./chrome-plugin
        run: npm install

      - name: run unit test
        working-directory: ./chrome-plugin
        if: success()
        run: npm run test

      - name: run build 
        working-directory: ./chrome-plugin
        if: success()
        run: npm run build
        
      - name: package
        working-directory: ./chrome-plugin
        if: success()
        run: tar -zcvf ./dist.tar.gz ./dist/ 
        
        
      - name: store artifact
        uses: actions/upload-artifact@v2
        with:
          name: ChromeExtension
          path: ./dist.tar.gz


